# Generated by Django 2.2.6 on 2019-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191012_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(blank=True),
        ),
    ]
